######################################################################
# Automatically generated by qmake (3.0) Sun Aug 23 19:31:11 2020
######################################################################

TEMPLATE = app
TARGET = 8-24-lianxi
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += mian.cpp
